name: Build and Push Docker image

on:
  push:
    branches:
      - 'azure-deploy'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/melody:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/melody:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/melody:buildcache,mode=max
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: docker stop symphony && docker run -d -p 80:5000 --name symphony --rm apekshaprabhu/melody:latest
